---
on:
  pull_request:
    branches:
      - main
      - production
      - next
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    branches:
      - main
      - production
      - next
  schedule:
    - cron: "0 3 * * *" # Nightly at 3 AM UTC
  workflow_dispatch:

name: docker
concurrency: docker

jobs:
  docker:
    name: Docker actions
    uses: RMI-PACTA/actions/.github/workflows/docker.yml@main
    with:
      do-check-r-sysdeps: false
      # dependabot forks the repo when making PRs, and doesn't have access
      # to secrets (like the deploy key) in actions. This allows the CI to
      # pass for dependabot PRs if the build succeeds.
      push-image: ${{ github.actor != 'dependabot[bot]' }}
