---
on:
  pull_request:
    branches:
      - main
      - production
      - next
  push:
    branches:
      - main
      - production
      - next

name: Node Package Checks
concurrency: node-package-checks

jobs:
  linting:
    name: "Linting"
    uses: ./.github/workflows/node-lint.yml

  formatting:
    name: "Formatting"
    uses: ./.github/workflows/node-prettier.yml

  unit-test:
    name: "Unit Tests"
    uses: ./.github/workflows/node-test.yml

  build:
    name: "Build"
    uses: ./.github/workflows/node-build.yml

  json-schema:
    name: "JSON Schema Validation"
    uses: ./.github/workflows/node-json-schema.yml
